- semana-0/sobre-mim/rede-sociais.txt
Semana0-aula4-5
- Sobre-mim
- Redes-sociais.txt
-São somente teste
> Redes-Sociais Adicionada

- semana-0/sobre-mim/musica.txt
Semana-0
- Sobre-mim
- Minha-bio.txt
- Muisica.txt
- Projeto simples somente um teste.
> Musica adicionada

- semana-0/sobre-mim/minha-bio.txt
Semana0-aula4-1
- Sobre-mim
- Minha-bio.txt
- Projeto simples somente um teste.
> adicionei a pasta semana0-aula4-1

- semana-0/sobre-mim/filme.txt
Semana0-aula4-3
- Pasta Sobre Mim
- Filmes.txt
-Teste
> Filmes Adicionado

- semana-0/sobre-mim/comida.txt
- Sobre-mim
- Comida.txt
- São somente teste
> Comida Preferida adicionada

- semana-0/projeto-onboarding/aprendizados.md
- Aprendizados.md
- Tudo esta funcionando.
> Adicionei projeto-onboarding

- semana1/strings-arrays/index.html
- semana1/strings-arrays/index.js
- Index.html (console)
- index.js (atividades)
- Esta tudo funcionando.
> Adicionei pasta strings-arrays

- semana1/operadores/index.html
- semana1/operadores/index.js
- index.html (console.log)
- index.js (atividades do dia)
- Esta tudo funcionando
> Adicionei a pasta operadores

- semana1/variaveis/index.html
- semana1/variaveis/index.js
Semana1
- index.html (console)
- index.js (atividades)
- Funciona todos exercícios
> Adicionei pasta semana1

- semana2/objetos/index.html
- semana2/objetos/index.js
-Index.html (Console.log)
-Index.js (Atividades)
- Tudo Funcionando
> Adicionei a Pasta Objetos

- semana1/funcoes/index.html
- semana1/funcoes/index.js
- index.html (console.log)
- index.js (atividades)
- Tudo esta funcionando
> Adicionei pasta funcoes

- semana2/funcoes-de-array/index.html
- semana2/funcoes-de-array/index.js
- index.html(console.log)
- index.js(atividades dos codigos)
- tudo esta funcionando
> Adicionei a pasta Funções de Array

- semana2/loops/index.html
- semana2/loops/index.js
- TUDO FUNCIONANDO
- TUDO FUNCIONANDO
> Adicionei a Pasta Loop

- semana2/condicionais/index.html
- semana2/condicionais/index.js
-index.html (console.log)
index.js (atividades)
- Uma atividade do desafio, o resto tudo funciona.
> Adicionei a pasta Condicionais

- semana2/blackjack/desafio.js
- semana2/blackjack/index.html
- semana2/blackjack/naoMexer.js
- semana2/blackjack/nossoJogo.js
- O jogo simples
- desafios (irei terminar)
> Adicionei o projeto BlackJack

- semana7/Labefy/Labefy.postman_collection.json
- semana7/Labefy/lsls
- Tudo esta Funcionando
- Tudo esta Funcionando
> Adicionei a pasta LabeFy junto com as atividades

- semana15/Express/.gitignore
- semana15/Express/package-lock.json
- semana15/Express/package.json
- semana15/Express/src/data.ts
- semana15/Express/src/index.ts
- semana15/Express/src/types.ts
- semana15/Express/text
- semana15/Express/tsconfig.json
> Atividades da Aula Express

- semana16/ToDoList/.gitignore
- semana16/ToDoList/package-lock.json
- semana16/ToDoList/package.json
- semana16/ToDoList/src/connection.ts
- semana16/ToDoList/src/index.ts
- semana16/ToDoList/tsconfig.json
> Projeto Back ToDoList

- semana17/servicos_Backend/.gitignore
- semana17/servicos_Backend/package.json
- semana17/servicos_Backend/src/app.ts
- semana17/servicos_Backend/src/data/connection.ts
- semana17/servicos_Backend/src/data/migrations.ts
- semana17/servicos_Backend/src/data/users.json
- semana17/servicos_Backend/src/endpoints/createAddressInfo.ts
- semana17/servicos_Backend/src/endpoints/createUser.ts
- semana17/servicos_Backend/src/index.ts
- semana17/servicos_Backend/src/services/getAddressInfo.ts
- semana17/servicos_Backend/src/services/mailTransporter.ts
- semana17/servicos_Backend/src/types.ts
- semana17/servicos_Backend/tsconfig.json
- tudo esta funcionando
- tudo esta funcionando
> Atividades de serviço Backend - endereço e mailTransporter

- semana15/APIs-REST/.gitignore
- semana15/APIs-REST/package.json
- semana15/APIs-REST/src/.txt
- semana15/APIs-REST/src/index.js
- semana15/APIs-REST/src/index.ts
- semana15/APIs-REST/tsconfig.json
> Atividades com APIs e REST

- semana16/Atividades-BancodeDados.md
- tudo funciona
- tudo funciona
> Atividade Banco de Dados

- semana16/Atividades-AprofundamentoSQL.md
- tudo funcionando
- tudo funcionando
> Atividades Aprofundamento Sql

- semana16/Atividades-knex-express/.gitignore
- semana16/Atividades-knex-express/Atividades-knex.md
- semana16/Atividades-knex-express/package-lock.json
- semana16/Atividades-knex-express/package.json
- semana16/Atividades-knex-express/src/app.ts
- semana16/Atividades-knex-express/src/connection.ts
- semana16/Atividades-knex-express/src/index.ts
- semana16/Atividades-knex-express/tsconfig.json
-Atividades de 1 a 6
- Atividade 7
> Atividades Introdução knex-express

- semana16/Atividades-Relacao-Sql/Atividades-RelacoesSql.md
- tudo funcionando
- tudo funcionando
> Atividades Relações SQL

- semana18/HerancaPolimorfismo/.gitignore
- semana18/HerancaPolimorfismo/package.json
- semana18/HerancaPolimorfismo/src/app.ts
- semana18/HerancaPolimorfismo/src/exercicioPolimorfismo/Client.ts
- semana18/HerancaPolimorfismo/src/exercicioPolimorfismo/Place.ts
- semana18/HerancaPolimorfismo/src/exerciciosHeranca/Customer.ts
- semana18/HerancaPolimorfismo/src/exerciciosHeranca/User.ts
- semana18/HerancaPolimorfismo/src/index.ts
- semana18/HerancaPolimorfismo/src/respostas.md
- semana18/HerancaPolimorfismo/tsconfig.json
- semana18/classesEncapsulamento/.vscode/launch.json
- Exercícios Herança 
- Exercícios Polimorfismo 1
- Desafios
- Exercicios Polimorfismo 2 a 6
> Atividades Herança e Polimorfismo

- semana19/Introducao-Autenticacao/.gitignore
- semana19/Introducao-Autenticacao/Respostas.md
- semana19/Introducao-Autenticacao/package-lock.json
- semana19/Introducao-Autenticacao/package.json
- semana19/Introducao-Autenticacao/src/app.ts
- semana19/Introducao-Autenticacao/src/data/connection.ts
- semana19/Introducao-Autenticacao/src/endpoints/createUser.ts
- semana19/Introducao-Autenticacao/src/endpoints/getUserId.ts
- semana19/Introducao-Autenticacao/src/endpoints/login.ts
- semana19/Introducao-Autenticacao/src/index.ts
- semana19/Introducao-Autenticacao/src/services/generateId.ts
- semana19/Introducao-Autenticacao/src/services/generateToken.ts
- semana19/Introducao-Autenticacao/src/services/getData.ts
- semana19/Introducao-Autenticacao/src/types.ts
- semana19/Introducao-Autenticacao/tsconfig.json
- Atividades 1 a 7
- 7 e Desafio
> Atividades Introdução de Autenticação

- semana20/Arquitetura de Software I/.gitignore
- semana20/Arquitetura de Software I/README.md
- semana20/Arquitetura de Software I/package-lock.json
- semana20/Arquitetura de Software I/package.json
- semana20/Arquitetura de Software I/src/app.ts
- semana20/Arquitetura de Software I/src/bussines/deleteUserIdBusiness.ts
- semana20/Arquitetura de Software I/src/bussines/getAllUserBusiness.ts
- semana20/Arquitetura de Software I/src/bussines/loginBussines.ts
- semana20/Arquitetura de Software I/src/bussines/signUpBussines.ts
- semana20/Arquitetura de Software I/src/connection.ts
- semana20/Arquitetura de Software I/src/controllers/deleteUserIdController.ts
- semana20/Arquitetura de Software I/src/controllers/getUserAllController.ts
- semana20/Arquitetura de Software I/src/controllers/loginController.ts
- semana20/Arquitetura de Software I/src/controllers/signUpController.ts
- semana20/Arquitetura de Software I/src/data/deleteUser.ts
- semana20/Arquitetura de Software I/src/data/getData.ts
- semana20/Arquitetura de Software I/src/data/getUserAll.ts
- semana20/Arquitetura de Software I/src/data/insertUser.ts
- semana20/Arquitetura de Software I/src/data/selectUserByEmail.ts
- semana20/Arquitetura de Software I/src/index.ts
- semana20/Arquitetura de Software I/src/services/authenticator.ts
- semana20/Arquitetura de Software I/src/services/hashManager.ts
- semana20/Arquitetura de Software I/src/services/idGenerator.ts
- semana20/Arquitetura de Software I/src/types/user.ts
- semana20/Arquitetura de Software I/tsconfig.json
- Todas as Atividades
- Todas as Atividades
> Atividade Arquitetura de Software I

- semana21/Testes-Automatizados-Typescript/.gitignore
- semana21/Testes-Automatizados-Typescript/Desafios.md
- semana21/Testes-Automatizados-Typescript/jest.config.js
- semana21/Testes-Automatizados-Typescript/package-lock.json
- semana21/Testes-Automatizados-Typescript/package.json
- semana21/Testes-Automatizados-Typescript/src/index.ts
- semana21/Testes-Automatizados-Typescript/src/model/User.ts
- semana21/Testes-Automatizados-Typescript/src/model/UserCasino.ts
- semana21/Testes-Automatizados-Typescript/src/tests.ts
- semana21/Testes-Automatizados-Typescript/tests/index.test.ts
- semana21/Testes-Automatizados-Typescript/tsconfig.json
- Exercicios 1 a 5
- Exercicios 6 a 9
> Atividades de Testes Automatizados com Typescript

- semana21/Teste-Unitarios-e-Mock/Respostas.md
- semana21/Teste-Unitarios-e-Mock/jest.config.js
- semana21/Teste-Unitarios-e-Mock/package-lock.json
- semana21/Teste-Unitarios-e-Mock/package.json
- semana21/Teste-Unitarios-e-Mock/src/performAttack.ts
- semana21/Teste-Unitarios-e-Mock/src/recoverCharacters.ts
- semana21/Teste-Unitarios-e-Mock/src/validateCharacter.ts
- semana21/Teste-Unitarios-e-Mock/tests/performAttack.test.ts
- semana21/Teste-Unitarios-e-Mock/tests/validateCharacter.test.ts
- semana21/Teste-Unitarios-e-Mock/tsconfig.json
- Exercicos 1 a 6
- Exercicos 7 e 8
> Atividades Testes Unitários e Mock
